---
# tasks file for apache_backend
- name: install apache
  yum:
    name: httpd
    state: present
  notify: enable httpd
- name: open ports in firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ ports }}"

- name: configure apache
  template:
    src: httpd.j2
    dest: "/etc/httpd/conf/httpd.conf"
  notify: restart httpd
